# Generated by Django 5.0.3 on 2024-11-16 08:26

import crea_app.storages
import posts_app.models
import posts_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_alter_headshot_banner_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshot',
            name='banner',
            field=models.ImageField(storage=crea_app.storages.UthoStorage(), upload_to=posts_app.utils.headshot_upload_to, validators=[posts_app.models.validate_media_type]),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, storage=crea_app.storages.UthoStorage(), upload_to=posts_app.utils.post_image_upload_to, validators=[posts_app.models.validate_media_type]),
        ),
    ]
