# Generated by Django 5.0.3 on 2024-10-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry_image', models.ImageField(upload_to='industry_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile_or_email', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('1', 'Admin'), ('2', 'Regular User')], max_length=1)),
                ('selected_industries', models.CharField(max_length=100)),
                ('selected_primary_industry', models.CharField(max_length=10)),
                ('selected_skills', models.CharField(max_length=100)),
                ('selected_primary_skill', models.CharField(max_length=10)),
                ('cover_image', models.ImageField(blank=True, upload_to='cover_images/')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skill_image', models.ImageField(upload_to='skill_images/')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.industry')),
            ],
        ),
    ]
