# Generated by Django 5.0.3 on 2024-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_mobile_or_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_or_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
