# Generated by Django 5.0.3 on 2024-10-24 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('project_link', models.URLField()),
                ('short_description', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('role_type', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=20)),
                ('skills', models.JSONField()),
                ('height', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=50)),
                ('script_file', models.FileField(blank=True, null=True, upload_to='scripts/')),
                ('script_url', models.URLField(blank=True, null=True)),
                ('audition_type', models.CharField(max_length=50)),
                ('offline_location', models.CharField(blank=True, max_length=255, null=True)),
                ('casting_call_date', models.DateField()),
                ('casting_call_end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=50)),
                ('project_id', models.CharField(max_length=255)),
                ('gig_title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('work_hours', models.IntegerField()),
                ('hours_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(max_length=50)),
                ('skills', models.JSONField()),
                ('progress_of_project', models.CharField(max_length=50)),
                ('work_method', models.CharField(max_length=50)),
                ('promotion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='media/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_tagline', models.CharField(max_length=255)),
                ('film_name', models.CharField(max_length=255)),
                ('film_role', models.CharField(max_length=255)),
                ('project_status', models.CharField(max_length=50)),
                ('progress_percentage', models.IntegerField()),
                ('project_type', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('team', models.JSONField()),
                ('media_files', models.JSONField()),
                ('hashtags', models.JSONField()),
                ('press_release_link', models.URLField(blank=True, null=True)),
                ('media_release_link', models.URLField(blank=True, null=True)),
                ('social_media_links', models.JSONField()),
                ('genre', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
