# Generated by Django 5.0.3 on 2024-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gigwork',
            name='hours_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gigwork',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('negotiable', 'Negotiable'), ('hourly', 'Hourly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gigwork',
            name='promotion',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('featured', 'Featured')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gigwork',
            name='work_method',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gigwork',
            name='work_type',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('contract', 'Contract'), ('part-time', 'Part-time'), ('full-time', 'Full-time')], max_length=50),
        ),
    ]
