# Generated by Django 5.0.3 on 2024-10-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_gigwork_updated_at_alter_gigwork_hours_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_overview', models.TextField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.FileField(upload_to='uploads/pan_cards/')),
                ('cancelled_cheque', models.FileField(upload_to='uploads/cheques/')),
            ],
        ),
        migrations.CreateModel(
            name='Apprenticeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('organisation_name', models.CharField(max_length=100)),
                ('apprenticeship_method', models.CharField(choices=[('individual', 'Individual'), ('organisation', 'Organisation')], max_length=20)),
                ('apprenticeship_title', models.CharField(max_length=100)),
                ('skills_list', models.JSONField()),
                ('apprenticeship_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('remote', 'Remote')], max_length=10)),
                ('type_of_work', models.CharField(choices=[('development', 'Development'), ('research', 'Research'), ('support', 'Support')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_responsibilities', models.TextField()),
                ('duration', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeships', to='forms.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('organisation_name', models.CharField(max_length=100)),
                ('intern_method', models.CharField(choices=[('individual', 'Individual'), ('organisation', 'Organisation')], max_length=20)),
                ('internship_title', models.CharField(max_length=100)),
                ('skills_list', models.JSONField()),
                ('internship_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('remote', 'Remote')], max_length=10)),
                ('type_of_work', models.CharField(choices=[('development', 'Development'), ('research', 'Research'), ('support', 'Support')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_responsibilities', models.TextField()),
                ('duration', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='forms.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('gst_status', models.CharField(max_length=3)),
                ('gst_number', models.CharField(max_length=15)),
                ('host_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('bank_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to='forms.bankdetails')),
                ('event_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to='forms.eventdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='forms.customuser')),
                ('uploads', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to='forms.uploads')),
            ],
        ),
    ]
