# Generated by Django 5.0.3 on 2024-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_uploads_cancelled_cheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigwork',
            name='progress_of_project',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=50),
        ),
        migrations.DeleteModel(
            name='PostFeed',
        ),
    ]
