# Generated by Django 5.0.3 on 2024-11-16 08:26

import crea_app.storages
import forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_project_artist_name_project_role_project_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_files',
            field=models.ImageField(blank=True, null=True, storage=crea_app.storages.UthoStorage(), upload_to=forms.utils.project_upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_files',
            field=models.FileField(blank=True, null=True, storage=crea_app.storages.UthoStorage(), upload_to=forms.utils.project_upload_to),
        ),
    ]
