# Generated by Django 5.0.3 on 2024-10-29 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0005_profile_view_count_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileview',
            name='time_viewed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
