# Generated by Django 5.0.3 on 2024-11-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0011_alter_documentupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlverification',
            name='status',
            field=models.CharField(default='Document pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dlverification',
            name='verify_status',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='passportverification',
            name='verify_status',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
