# Generated by Django 5.0.3 on 2024-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0014_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unionassociation',
            name='member_since',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
