# Generated by Django 5.0.3 on 2024-11-15 11:43

import crea_app.storages
import userprofile_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0016_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.FileField(blank=True, null=True, storage=crea_app.storages.UthoStorage(), upload_to=userprofile_app.models.cover_image_upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, storage=crea_app.storages.UthoStorage(), upload_to=userprofile_app.models.profile_image_upload_to),
        ),
    ]
