# Generated by Django 5.0.3 on 2024-11-16 08:26

import crea_app.storages
import userprofile_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0017_alter_profile_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.FileField(blank=True, null=True, storage=crea_app.storages.UthoStorage(), upload_to=userprofile_app.utils.document_upload_to),
        ),
    ]
