# Generated by Django 5.0.3 on 2024-10-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crea_app', '0002_onboardingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='onboardingimage',
            name='image',
            field=models.ImageField(default='onboarding-images/default.jpg', upload_to='onboarding-images/'),
        ),
    ]
