# Generated by Django 5.0.3 on 2024-10-24 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry_image', models.ImageField(upload_to='industry_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skill_image', models.ImageField(upload_to='skill_images/')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profile_app.industry')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_or_email', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('1', 'Admin'), ('2', 'Regular User')], max_length=1)),
                ('selected_industries', models.CharField(max_length=100)),
                ('selected_primary_industry', models.CharField(max_length=10)),
                ('selected_skills', models.CharField(max_length=100)),
                ('selected_primary_skill', models.CharField(max_length=10)),
                ('cover_image', models.ImageField(blank=True, upload_to='cover_images/')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_app_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
