# Generated by Django 5.0.3 on 2024-10-24 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_or_email', models.CharField(max_length=255)),
                ('aadhar_cn', models.CharField(max_length=12, unique=True)),
                ('aadhar_fname', models.CharField(max_length=255)),
                ('verify_status', models.CharField(default='Document pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicenseVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_or_email', models.CharField(max_length=255)),
                ('dl_ln', models.CharField(max_length=15, unique=True)),
                ('dl_fname', models.CharField(max_length=255)),
                ('dl_isscstate', models.CharField(max_length=255)),
                ('verify_status', models.CharField(default='Document pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassportVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_or_email', models.CharField(max_length=255)),
                ('ps_cn', models.CharField(max_length=12, unique=True)),
                ('ps_fname', models.CharField(max_length=255)),
                ('ps_isscountry', models.CharField(max_length=255)),
                ('ps_dateexp', models.DateField()),
                ('verify_status', models.CharField(default='Document pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
