"""
Django settings for crea project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from pathlib import Path
from decouple import config, Csv
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p=h!ot2ea=8=vco@i5wu9hg12*z0ha3d(yr$&3%za7qhrc_^ih'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crea_app',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'storages',
    'b2sdk',
    'userprofile_app',
    'social_app',
    'forms',
    'posts_app',
    'save_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crea_db',
        'USER': 'root',
        'PASSWORD': 'ansil',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
SHOW_SWAGGER = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'crea_app.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_COOKIE_SECURE = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'connect@artiztnetwork.com'  # your email
EMAIL_HOST_PASSWORD = 'istz tnfx jjwy cslm'  # App Password if 2FA is enabled
DEFAULT_FROM_EMAIL = 'connect@artiztnetwork.com'



B2_ACCOUNT_ID = '0055668acec6f400000000007'  # Replace with your Account ID
B2_APPLICATION_KEY = 'K005CQRVl9H+5mxfqK0DE0MtezgziUU'  # Replace with your Application Key
B2_BUCKET_ID = 'f576e6c88aec9eec962f0410'
B2_FOLDER_NAME = 'onboarding-images'
B2_STORAGE_CLASS = 'crea_app.backblaze_storage.B2Storage'
B2_BUCKET_NAME = "crea-onboarding"
END_POINT_URL = "s3.us-east-005.backblazeb2.com"

# B2_ACCOUNT_ID = '005c8a756e62b540000000001'  # Replace with your Account ID
# B2_APPLICATION_KEY = 'K005+sxUQVfnQvXNxw4NL6F3+nzz9DA'  # Replace with your Application Key
# B2_BUCKET_ID = 'ecb87a3765e62e56923b0514'
# B2_STORAGE_CLASS = 'crea_app.backblaze_storage.B2Storage'
# B2_BUCKET_NAME = "crea-b2"
# END_POINT_URL = "s3.us-east-005.backblazeb2.com"
# REGION = "us-east-005"

UTHO_STORAGE_ACCESS_KEY = 'hdxCta4HqMbKpIZPR8vO2jWUe3E7QNycGgol'
UTHO_STORAGE_SECRET_KEY = 'XRFIic7uqE3S8mtW59V2Ygn6BrhGfUQLwTyj'
UTHO_STORAGE_BUCKET_NAME = 'creap2'
UTHO_STORAGE_REGION = 'innoida'

DEFAULT_FILE_STORAGE = 'crea_app.storages.UthoStorage'

DJANGO_SETTINGS_MODULE='crea.settings'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

load_dotenv()

MSG91_API_KEY = os.getenv('MSG91_API_KEY')
MSG91_SMS_TEMPLATE_ID = os.getenv('MSG91_SMS_TEMPLATE_ID')
MSG91_SMS_SENDER_ID = os.getenv('MSG91_SMS_SENDER_ID')
MSG91_EMAIL_SENDER_NAME = os.getenv('MSG91_EMAIL_SENDER_NAME')
import os
import firebase_admin
from firebase_admin import credentials
from firebase_admin.exceptions import FirebaseError
import logging
import base64


# Fix Base64 String Function
def fix_base64_string(token):
    # Add padding to make the length a multiple of 4
    padding_needed = len(token) % 4
    if padding_needed:
        token += '=' * (4 - padding_needed)
    return token

# Decode JWT Function
def decode_jwt(token):
    parts = token.split('.')
    # Decode the payload
    if len(parts) != 3:
        print("Invalid token format.")
        return None
    try:
        payload = base64.urlsafe_b64decode(fix_base64_string(parts[1]))
        print("Decoded Payload:", payload)
    except Exception as e:
        print("Error decoding token:", e)

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load Firebase service account key
BASE_DIR = os.path.dirname(os.path.abspath(__file__))  # This points to the directory containing the JSON
cred_path = os.getenv("FIREBASE_CREDENTIALS_PATH", os.path.join(BASE_DIR, "serviceAccountKey.json"))  # Use environment variable

# Check if the credential file exists
if not os.path.exists(cred_path):
    raise FileNotFoundError(f"The service account key file does not exist at the path: {cred_path}")

# Initialize Firebase
try:
    cred = credentials.Certificate(cred_path)
    firebase_app = firebase_admin.initialize_app(cred)
    logger.info("Firebase initialized successfully.")
except FirebaseError as e:
    logger.error(f"Error initializing Firebase: {e}")
except Exception as e:
    logger.error(f"An unexpected error occurred: {e}")
